		INCLUDE 'MC9S08JM16.INC' 
	
;INTERUPCIONES 	
KBIE	EQU		1
KBACK	EQU		2
IRQACK	EQU	2
;LCD
RS		EQU	0		;Define bit 0 del PTD
ENABLE	EQU	1		;Define bit 1 del PTD
;MATRIZ
;RELOJ INTERNO
LOCK	EQU	6		;Bit 6 del registro MCGSC

		ORG 	0B0H  ;Direccion de RAM  (Variables)
			
TABLERO   DS 21
FILA_C    DS 1
COLUM_C    DS 1
CUADRO	DS 	4
FUENT	DS	1	
DEST	DS 	1
TEMP	DS 	1
N1		DS	1
N2		DS	1
		ORG		0C000H; Direccion de RAM  (Memoria para programa)

INICIO:	MOV		#2H,COLUM_C	;
		
		MOV		#00010000B,CUADRO
		MOV		#00010000B,CUADRO+1
		MOV		#00011000B,CUADRO+2
		MOV		#00000000B,CUADRO+3
		
		;-------FUENTE CAMBIA----------		
		MOV		CUADRO+0,FUENT;
		MOV		CUADRO+3,DEST;		
		MOV		COLUM_C,N1;
		MOV		COLUM_C,N2;
		JSR		ROTAR;1
		MOV		DEST,CUADRO+3;
		;---------------------------------------
		;MOV		CUADRO+3,DEST; COMO SE REPITE NO ES NECESARIO
		;MOV		N2,N1; COMO YA ESTA NO SE MODIFICA
		LDA		COLUM_C;
		ADD		#3H;
		STA		N2;
		JSR		ROTAR;2
		MOV		DEST,CUADRO+3; EL DESTINO SE CARGA 
		;------------------------------
		MOV		CUADRO+0,DEST
		MOV		N2,N1; SE CARGA N2 A N1 POR QUE EN ESTE CASO SON IGUALES
		;LDA		COLUM_C; N2 NO SE MODIFICA
		;ADD		#3H;
		;STA		N2;
		JSR		ROTAR;3
		MOV		DEST,CUADRO+0;
		;------------------------------
		;MOV	CUADRO+0,DEST; YA SE CARGO ENTONCES NO SE HACE
		;MOV		N2,N1; N1 PERMANECE IGUAL
		MOV		COLUM_C,N2;
		JSR		ROTAR;4
		MOV		DEST,CUADRO+0; EL DESTINO SE CARGA 
		
		;---------- LA FUENTE CAMBIA----
		MOV		CUADRO+1,FUENT;
		MOV		CUADRO+3,DEST;
		MOV		COLUM_C,N1;
		LDA		COLUM_C;
		ADD		#1H;
		STA		N2;
		JSR		ROTAR;5
		MOV		DEST,CUADRO+3; SE CARGA EL DESTINO MODIFICADO
		;----------------------
		MOV		CUADRO+2,DEST;
		MOV		N2,N1;
		LDA		COLUM_C; 
		ADD		#3H;
		STA		N2;N2 = COLUM+3
		JSR		ROTAR;6 
		MOV		DEST,CUADRO+2; SE CARGA EL DESTINO MODIFICADO
		;------------------------
		MOV		CUADRO+0,DEST;
		MOV		N2,N1;
		LDA		COLUM_C; 
		ADD		#2H;
		STA		N2;N2 = COLUM+2
		JSR		ROTAR; 7
		MOV		DEST,CUADRO+0; SE CARGA EL DESTINO MODIFICADO
		;------------------------
		MOV		CUADRO+1,DEST;
		MOV		N2,N1;
		MOV		COLUM_C,N2; N2 = COLUMNA
		JSR		ROTAR; 8
		MOV		DEST,CUADRO+1; SE CARGA EL DESTINO MODIFICADO
		
		;---------- LA FUENTE CAMBIA----
		MOV		CUADRO+2,FUENT;
		MOV		CUADRO+3,DEST;
		MOV		COLUM_C,N1;
		LDA		COLUM_C;
		ADD		#2H;
		STA		N2;
		JSR		ROTAR;9
		MOV		DEST,CUADRO+3; SE CARGA EL DESTINO MODIFICADO
		;----------------------
		MOV		CUADRO+1,DEST;
		MOV		N2,N1;
		LDA		COLUM_C; 
		ADD		#3H;
		STA		N2;N2 = COLUM+3
		JSR		ROTAR;10 
		MOV		DEST,CUADRO+1; SE CARGA EL DESTINO MODIFICADO
		;------------------------
		MOV		CUADRO+0,DEST;
		MOV		N2,N1;
		LDA		COLUM_C; 
		ADD		#1H;
		STA		N2;N2 = COLUM+1
		JSR		ROTAR; 11
		MOV		DEST,CUADRO+0; SE CARGA EL DESTINO MODIFICADO
		;------------------------
		MOV		CUADRO+2,DEST;
		MOV		N2,N1;
		MOV		COLUM_C,N2; N2 = COLUMNA
		JSR		ROTAR; 
		MOV		DEST,CUADRO+2; SE CARGA EL DESTINO MODIFICADO
		;---------- LA FUENTE CAMBIA----
		MOV		CUADRO+1,FUENT;
		MOV		CUADRO+2,DEST;
		LDA		COLUM_C;
		ADD		#1H;
		STA		N1; N1=COLUM+1
		MOV		N1,N2; N2=N1
		JSR		ROTAR;13
		MOV		DEST,CUADRO+2; SE CARGA EL DESTINO MODIFICADO
		;----------------------
		;MOV		CUADRO+2,DEST; YA ESTA ASIGNADO
		;MOV		N2,N1; YA ESTA ASIGNADO
		LDA		COLUM_C; 
		ADD		#2H;
		STA		N2;N2 = COLUM+2
		JSR		ROTAR;14 
		MOV		DEST,CUADRO+2; SE CARGA EL DESTINO MODIFICADO
		;------------------------
		MOV		CUADRO+1,DEST;
		MOV		N2,N1;
		;N2 = COLUM+1 YA ESTA ASIGNADO
		JSR		ROTAR; 15
		MOV		DEST,CUADRO+1; SE CARGA EL DESTINO MODIFICADO
		;------------------------
		;MOV		CUADRO+1,DEST; YA ESTA ASIGNADO
		MOV		N2,N1;
		LDA		COLUM_C; 
		ADD		#1H;
		STA		N2;N2 = COLUM+2
		JSR		ROTAR; 16
		MOV		DEST,CUADRO+1; SE CARGA EL DESTINO MODIFICADO		
		JMP		*



;-------INICIO DE SUBRUTINA ROTAR----------
;------------------------------------------
ROTAR:	MOV		DEST,TEMP;
		LDA 	N1
		CBEQA	#7H,N17;
		CBEQA	#6H,N16;
		CBEQA	#5H,N15;
		CBEQA	#4H,N14;
		CBEQA	#3H,N13;
		CBEQA	#2H,N12;		
		CBEQA	#1H,N11;		
N10:	BRCLR	0,FUENT,DEST0;PREGUNTA
		JSR		SETN2; LLAMA A SET N2 PARA QUE PONGA EL DESTINO EN 1
		JMP		FINR		
DEST0:	
		;BCLR	0,DEST
		JMP		FINR
		
N11:	BRCLR	1,FUENT,DEST1;PREGUNTA
		JSR		SETN2; LLAMA A SET N2 PARA QUE PONGA EL DESTINO EN 1
		JMP		FINR		
DEST1:	JSR		CLRN2; LLAMA A CLR N2 ARA PONER EL DESTINO EN 0
		JMP		FINR
		
N12:	BRCLR	2,FUENT,DEST2;PREGUNTA
		JSR		SETN2; LLAMA A SET N2 PARA QUE PONGA EL DESTINO EN 1
		JMP		FINR		
DEST2:	JSR		CLRN2; LLAMA A CLR N2 ARA PONER EL DESTINO EN 0
		JMP		FINR
		
N13:	BRCLR	3,FUENT,DEST3;PREGUNTA
		JSR		SETN2; LLAMA A SET N2 PARA QUE PONGA EL DESTINO EN 1
		JMP		FINR		
DEST3:	JSR		CLRN2; LLAMA A CLR N2 ARA PONER EL DESTINO EN 0
		JMP		FINR
		
N14:	BRCLR	4,FUENT,DEST4;PREGUNTA
		JSR		SETN2; LLAMA A SET N2 PARA QUE PONGA EL DESTINO EN 1
		JMP		FINR		
DEST4:	JSR		CLRN2; LLAMA A CLR N2 ARA PONER EL DESTINO EN 0
		JMP		FINR
		
N15:	BRCLR	5,FUENT,DEST5;PREGUNTA
		JSR		SETN2; LLAMA A SET N2 PARA QUE PONGA EL DESTINO EN 1
		JMP		FINR		
DEST5:	JSR		CLRN2; LLAMA A CLR N2 ARA PONER EL DESTINO EN 0
		JMP		FINR
		
N16:	BRCLR	6,FUENT,DEST6;PREGUNTA
		JSR		SETN2; LLAMA A SET N2 PARA QUE PONGA EL DESTINO EN 1
		JMP		FINR		
DEST6:	JSR		CLRN2; LLAMA A CLR N2 ARA PONER EL DESTINO EN 0
		JMP		FINR
		
N17:	BRCLR	7,FUENT,DEST7;PREGUNTA
		JSR		SETN2; LLAMA A SET N2 PARA QUE PONGA EL DESTINO EN 1
		JMP		FINR		
DEST7:	JSR		CLRN2; LLAMA A CLR N2 ARA PONER EL DESTINO EN 0
FINR:	MOV		TEMP,FUENT	 ;
		RTS;RETORNA

;-------INICIO DE SUBRUTINA SET BIT N2------
;------------------------------------------
SETN2:	LDA 	N2
		CBEQA	#7H,N2S7;
		CBEQA	#6H,N2S6;
		CBEQA	#5H,N2S5;
		CBEQA	#4H,N2S4;
		CBEQA	#3H,N2S3;
		CBEQA	#2H,N2S2;		
		CBEQA	#1H,N2S1;		
N2S0:	BSET	0,DEST
		JMP		SETFIN
N2S1:	BSET	1,DEST
		JMP		SETFIN
N2S2:	BSET	2,DEST
		JMP		SETFIN
N2S3:	BSET	3,DEST
		JMP		SETFIN
N2S4:	BSET	4,DEST
		JMP		SETFIN
N2S5:	BSET	5,DEST
		JMP		SETFIN
N2S6:	BSET	6,DEST
		JMP		SETFIN
N2S7:	BSET	7,DEST		
SETFIN:	RTS;

;-------INICIO DE SUBRUTINA CLR BIT N2------
;------------------------------------------
CLRN2:	LDA 	N2
		CBEQA	#7H,N2C7;
		CBEQA	#6H,N2C6;
		CBEQA	#5H,N2C5;
		CBEQA	#4H,N2C4;
		CBEQA	#3H,N2C3;
		CBEQA	#2H,N2C2;		
		CBEQA	#1H,N2C1;		
N2C0:	BCLR	0,DEST
		JMP		CLRFIN
N2C1:	BCLR	1,DEST
		JMP		CLRFIN
N2C2:	BCLR	2,DEST
		JMP		CLRFIN
N2C3:	BCLR	3,DEST
		JMP		CLRFIN
N2C4:	BCLR	4,DEST
		JMP		CLRFIN
N2C5:	BCLR	5,DEST
		JMP		CLRFIN
N2C6:	BCLR	6,DEST
		JMP		CLRFIN
N2C7:	BCLR	7,DEST		
CLRFIN:	RTS; RETORNA

TABLA:FCB '0','1','2','3','4','5','6','7','8','9',0FFH


;-------------------------------------------------------------				
;------POSICION DE INICIO----------------------------------
		ORG     0FFFEH
		FDB		INICIO

